apiVersion: v1
kind: ServiceAccount
metadata:
  name: kairos-sa
  namespace: kairos
  annotations:
    # Workload Identity — maps to GCP service account provisioned in Terraform.
    iam.gke.io/gcp-service-account: kairos-gke@PROJECT_ID.iam.gserviceaccount.com
